# docker-compose.yml

version: '3.8'
services:
  app: 
    build: .
    ports: - "3000:3000"
    environment: 
      - DATABASE_URL: ${DATABASE_URL}
    depends_on: 
      - postgres
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: